### PR TITLE
Updates to 1-0-stable

### PR DESCRIPTION
**Pull request by juozasg**
Hi radar,

I've cherry picked few commits from master and added some of my own commits on top of your 1-0-stable branch. There are no major changes, mainly it involves moving some dependencies (kaminary, forem-redcarpet) into development gemspec. A small (non-active) bug in post.rb. There is one major dependency change (from state_machine to workflow) which I included to make other cherry picks from master possible without any patching.

Also picked something from master to make the tests pass in 1.8.7 and updated the Gemfile.lock with new dependencies.

The main reason for all these changes is to have a clean 1-0 branch that is ready to integrate with refinery-cms. 

I'm not sure if that matches your development process at all, but hope you pick these into 1-0-stable. I'm working on forums/intranet site based on forem and refinery and would like to be able to build on a stable foundation as I imagine others would like as well. 

Thank you,
Juozas

### CODE REVIEW

**Comment by parndt** [comment]
Thanks! Did you mean to target 1-0-stable branch for this?

**Comment by juozasg** [comment]
Note: this is a request to merge int your 1-0-stable, not your master like github heading says

**Comment by juozasg** [comment]
yes, i did :)

**Comment by parndt** [comment]
wrong way around :D hehe

**Comment by juozasg** [comment]
just cherry picked this one for 1-0-stable also:

83e86b6 Extend will_paginate only when ActiveRecord::Base is loaded

it's needed to work with latest rails

**Comment by juozasg** [comment]
Hey parndt,

 I assume since this is closed you are not interested in including these changes in radar/1-0-stable? If that's the case can you include few of these in master (ones that are not already there)? When are you planning to update 1-0-stable btw?

**Comment by parndt** [comment]
You're asking us to merge commits from your 1-0-stable into our master - is that correct?

At the top it says:

juozasg wants someone to merge 10 commits into radar:master from juozasg:1-0-stable

**Comment by juozasg** [comment]
Sorry, this is an incorrect pull request. Here's the corrected one: https://github.com/radar/forem/pull/226. I've added few more small commits from master and update the pull request description.

**Comment by parndt** [comment]
thanks :-)

**Pull request closed without merging**
