### PR TITLE
Display page titles

### PR DESCRIPTION
**Pull request by fracek**
I implemented page titles as indicated in #146, every view calls an helper to set the title for that page.

### CODE REVIEW

**Comment by fracek** [comment]
Sorry I thought forem was ruby 1.9+.

Do you want me to change to use the hashrocket and make another pull request? To maintain a clean history.

**Comment by radar** [comment]
No need for another pull request. Please just revert to using hashrocket syntax and force-push a fixed commit to your branch. That will update this pull request.

**Comment by parndt** [comment]
Does this have to happen in the view template?

**Comment by fracek** [comment]
I think it's where it makes more sense, if you think it's better doing it another way I will change it.

**Comment by Spaceghost** [comment]
You could put it on the view object itself if you like.

**Pull request closed without merging**
