### PR TITLE
Forem user methods

### PR DESCRIPTION
**Pull request by mauriciopasquier**
Patch for #451

Please, let me know if you think I went too far by touching those spec files related to Refunery::Yooser. I just needed a custom model to test the defaults.

### CODE REVIEW

**Comment by radar** [comment]
Hey @mauriciopasquier, sorry that I've not reviewed this sooner. I tried applying this to master today and ran into a couple of conflicts. Could you please review these and amend the PR?

**Comment by mauriciopasquier** [comment]
No problem! I'll take a look at it this weekend

**Comment by mauriciopasquier** [comment]
Ok, I rebased but can't run tests because of this:

```
rake aborted!
undefined method `theme=' for Forem:Module
<path>/bundler/gems/forem-theme-base-3efec35538c3/lib/forem-theme-base.rb:6:in `<class:Engine>'
```

Should I point the Gemfile to another repo/branch/theme, or what? Commenting that line seems to work but then I got a lot of unrelated (I hope) Capybara errors..

**Comment by radar** [comment]
@mauriciopasquier My bad. I had deprecated that method over the weekend (in favour for what is now mentioned on [the "Theming" wiki page](https://github.com/radar/forem/wiki/Theming)). I hadn't removed it from my forem-theme-base repo yet, but I have done that now.

Please try again.

**Comment by mauriciopasquier** [comment]
Awesome, everything's green now! Just rebased, updated the readme and forcepushed :)

**Comment by radar** [comment]
Thanks @mauriciopasquier, the code looks good to me. I've added this to master and rails4.

**Comment by mauriciopasquier** [comment]
\o/

**Pull request closed without merging**
