### PR TITLE
GH #202: Sign in path is configurable

### PR DESCRIPTION
**Pull request by kamarcum**
If this is merged, we'll also need an update on https://github.com/radar/forem/wiki/Configuration

### CODE REVIEW

**Comment by knewter** [comment]
Tests pass.  Merging and updating wiki.

**Comment by knewter** [comment]
@radar, @parndt,, @kamarcum - does the change I made to the wiki re: this setting seem sufficient / actually tell the truth?

https://github.com/radar/forem/wiki/Configuration

**Comment by knewter** [comment]
@kamarcum by the way, thanks tons for the contribution!

**Comment by parndt** [comment]
Seems ok but I skimmed it

**Pull request merged**
