### PR TITLE
Touch topics when posts are updated to enable ordering by post without a...

### PR DESCRIPTION
**Pull request by jgadbois**
... join

This solution will probably require a rake task or migration for existing installations.

### CODE REVIEW

**Comment by radar** [comment]
Why would this require a rake task or migration for existing installations?

**Comment by jgadbois** [comment]
Because in existing installations topic updated_at will be the same as topic created_at, causing the topics to be ordered by creation instead of by topics with the most recent posts.  Once another post was added it would move up to the top correctly.

**Comment by radar** [comment]
Rightio, well use `Forem::Topic.find_each` inside that migration to fix it then. Gogo ;)

**Comment by jgadbois** [comment]
@radar - added migration

**Pull request closed without merging**
