### PR TITLE
Adding subscriptions

### PR DESCRIPTION
**Pull request by AstonJ**
Added the first part of the subscriptions (subcription_spec, subscription model and associations) under guidance from Radar.

### CODE REVIEW

**Comment by parndt** [comment]
Was it intentional to delete most of spec/dummy's migrations ?

**Comment by AstonJ** [comment]
No Philip, I was having trouble running migrations so Ryan told me to run:

bundle exec rake -f spec/dummy/Rakefile forem:install:migrations

Then:

bundle exec rake -f spec/dummy/Rakefile db:drop db:create db:migrate db:test:prepare

Perhaps that's what deleted them? 

(Ryan did actually check this - but he hasn't mentioned anything about the dummy/migrations :/)

**Comment by parndt** [comment]
Maybe when @radar wakes up he can comment :-)

**Comment by AstonJ** [comment]
We might be waiting a while... last I heard of him he was legless lol

**Comment by radar** [comment]
Not so legless today.

By running `bundle exec rake -f spec/dummy/Rakefile forem:install:migrations` it would have copied over the migration for the `subscriptions` table to the `spec/dummy/db/migrate` folder. This then should have been added to Git, rather than the migrations in dummy being removed. The reason for this is because there's more than the Forem migrations in dummy: There's also migrations that set up stuff for the dummy application's users table which we most definitely don't want to delete.

**Comment by radar** [comment]
To restore the migrations I ran this little command. Was a good exercise in learning more about Git.

`git checkout <sha that deleted commits>^ -- spec/dummy/db/migrate/20110625220405_create_forem_forums.rb
spec/dummy/db/migrate/20110625220406_create_forem_topics.rb spec/dummy/db/migrate/20110625220407_create_forem_posts.rb spec/dummy/db/migrate/20110625220408_add_reply_to_to_forem_posts.rb spec/dummy/db/migrate/20110625220409_add_locked_to_forem_topics.rb spec/dummy/db/migrate/20110625220410_add_pinned_to_forem_topics.rb spec/dummy/db/migrate/20110625220411_add_forem_views.rb spec/dummy/db/migrate/20110625220412_add_updated_at_and_count_to_forem_views.rb spec/dummy/db/migrate/20110708030915_add_email_to_users.rb spec/dummy/db/migrate/20110625220412_add_updated_at_and_count_to_forem_views.rb spec/dummy/db/migrate/20110828132917_add_hidden_to_forem_topics.rb spec/dummy/db/migrate/20111026062441_add_devise_to_users.rb spec/dummy/db/migrate/20111026132103_add_login_back_to_users.rb spec/dummy/db/migrate/20111026132225_add_forem_admin_to_users.rb spec/dummy/db/migrate/20111108032747_add_indexes_to_topics_posts_views.rb spec/dummy/db/migrate/20111108032748_create_forem_categories.rb spec/dummy/db/migrate/20111108032749_add_category_id_to_forums.rb`

**Comment by radar** [comment]
Added in @1edab8d0a1386bab8ea604a98e823183a695a057 and @f341b3b961c989b44d1883c136477ef08852511c.

Thanks Aston!

**Comment by jgadbois** [comment]
I'm not seeing this in master (or a branch for that matter).  Once this gets merged I'll start on the front end.

**Comment by radar** [comment]
Added on master as @6a53aff544b6c4de3415dbe78366fd92a22d5258 and @cda7ea265367470483985ab11a1c5ed3185bf2b6. Don't know where I got the other two refs from :\

**Pull request closed without merging**
