### PR TITLE
Moderation queue

### PR DESCRIPTION
**Pull request by radar**
This is the work from #433, moved to the main repository since the [original owner gave up](https://github.com/radar/forem/pull/433#issuecomment-18812715).

---
- [x] Write tests for TopicsController moderation queue mailers
- [ ] Write tests for the mailer itself.
- [ ] Ensure users who are within a forum's `moderators` group get emailed.
- [ ] Include post text within moderation email, unlike Google Groups.

### CODE REVIEW

**Comment by parndt** [comment]
Improved!

**Comment by parndt** [comment]
This is an obvious place where we can maybe DRY up the entire moderation email process, given that both controllers are doing remarkably similar things.  But we can do that later.

**Comment by radar** [comment]
Looking good!

**Comment by parndt** [comment]
Over to you again @radar

**Pull request closed without merging**
