### PR TITLE
Don't need to add forem_admin field - forem_admin? method is enough.

### PR DESCRIPTION
**Pull request by LegendSzymon-P**
Just added to readme that you can instead of adding forem_admin field, add simply forem_admin? method to the User model.

### CODE REVIEW

**Comment by nruth** [comment]
I think this is a sensible update. We're also using a virtual attribute rather than a boolean in the db.

**Comment by bambielli** [comment]
Question: how do we set that? I'm assuming it is in the forem controller, which we don't have access to? 

Our log-in system for our app isn't using devise...we are just setting a session variable when users log in that is set to their profile id. We are also setting a session[:admin] = true if the admin is logged in.

We would like it if we could just substitute forem_admin with session[:admin].

**Comment by radar** [comment]
Hi @bambielli,

You can set that by overriding the `forem_admin?` method in `Forem::ApplicationController`:

**app/decorators/forem/application_controller_decorator.rb**

``` ruby
Forem::ApplicationController.class_eval do
  def forem_admin?
    session[:admin]
  end
end
```

**Comment by jtdavis247** [comment]
how do you create a forem_admin? would i do it in the cole like this...

Toddirb(main):011:0> admin = Admin.create! do |u|
irb(main):012:1\* u.email = 'jj@gmail.com'
irb(main):013:1> u.password = 'lakers34'
irb(main):014:1> u.password_confirmation = 'lakers34'
irb(main):015:1> u.profile_name = 'lakers34'
irb(main):016:1> u.forem_admin = true
irb(main):017:1> end

**Comment by radar** [comment]
@jtdavis247 Yes, that's right.

**Comment by jtdavis247** [comment]
I wonder why its still saying access denied when i try to view admin controls even though i am logged in as the admin i created....

**Comment by jtdavis247** [comment]
it says it doesnt like the line u.forem_admin = true in the console

**Comment by radar** [comment]
@jtdavis247 What do you mean it "doesn't like"? Show us the output exactly please.

**Comment by jtdavis247** [comment]
when I type:
1.9.3-p448 :016 > admin = Admin.create! do |u|
1.9.3-p448 :017 >     u.email = 'sampleemail@gmail.com'
1.9.3-p448 :018?>   u.password = 'password'
1.9.3-p448 :019?>   u.password_confirmation = 'password'
1.9.3-p448 :020?>   u.forem_admin = true
1.9.3-p448 :021?>   end

I get this error 

NoMethodError: undefined method `forem_admin=' for #<Admin:0x007f9f3ae20ac8>
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/activemodel-3.2.14/lib/active_model/attribute_methods.rb:407:in`method_missing'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.14/lib/active_record/attribute_methods.rb:149:in `method_missing'
    from (irb):20:in`block in irb_binding'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/activerecord-3.2.14/lib/active_record/validations.rb:40:in `create!'
    from (irb):16
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.14/lib/rails/commands/console.rb:47:in`start'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.14/lib/rails/commands/console.rb:8:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.14/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

I have been trying to get access to the admin panel for days not but i can't get forem to recognize my admin i created in the DB as an admin. I am not sure what I am missing. 

admin model:

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

user model:
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                   :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name , presence: true
  validates :profile_name, presence: true,
            uniqueness: true, format: { with: /^[a-zA-Z0-9_-]+$/, 
                                        message: 'Must be formatted without spaces.'
                                      }

  validates :email , presence: true, 
            uniqueness: true

  validates :password , presence: true

  has_many :statuses
  has_many :topics

  def full_name
    first_name + " " + last_name
end

   def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)

```
"http://gravatar.com/avatar/#{hash}"
```

   end
end

application controller:

class ApplicationController < ActionController::Base

  def forem_user
    current_user
  end
  helper_method :forem_user

  protect_from_forgery
end

application_controller_decorator.rb:

Forem::ApplicationController.class_eval do
  def forem_admin?
    session[:admin]
  end
end

I have not changed any of my controllers that came with devise.

when i try to access the admin pages after logging in through admins/sign_in path  it says access denied. not sure what to do if you knew what was going on I would be eternally greatful! Thanks so much for your time!

**Comment by radar** [comment]
Can you please show us the migration from your app which adds the forem_admin column? I suspect it's only adding it to the users table

**Comment by jtdavis247** [comment]
there are two migrations you could be speaking of 

first:
class AddAdminToUsers < ActiveRecord::Migration
  def self.up
    add_column :users, :admin, :boolean, :default => true
  end

  def self.down
    remove_column :users, :admin
  end

Second:

# This migration comes from forem (originally 20120616193446)

class AddForemAdmin < ActiveRecord::Migration
  def change
    unless column_exists?(user_class, :forem_admin)
      add_column user_class, :forem_admin, :boolean, :default => true
    end
  end

  def user_class
    Forem.user_class.table_name.downcase.to_sym
  end
end

**Comment by radar** [comment]
Please remember to format code using 4 space indentation or wrapping it in triple backticks so it's neater.

This migration is quite clearly adding the field to only your users table. You will need to create another migration to add this field to your admins table.

**Comment by jtdavis247** [comment]
k I just created a migration and here is what it looks like. 

```
class AddAdminForemToAdmin < ActiveRecord::Migration
def self.up
add_column :admins, :forem_admin, :boolean, :default => true
end

def self.down
remove_column :admins, :forem_admin
end
end
```

I then when in and made sure I created an admin by doing this in my console

```
1.9.3-p448 :016 > admin = Admin.create! do |u|
1.9.3-p448 :017 > u.email = 'sampleemail@gmail.com'
1.9.3-p448 :018?> u.password = 'password'
1.9.3-p448 :019?> u.password_confirmation = 'password'
1.9.3-p448 :020?> u.forem_admin = true
1.9.3-p448 :021?> end
```

and it worked great it appeared.

Then I went in to access the admin pages again and I am still getting access denied. So sorry about the hassle and thank you very much for your help.

**Comment by radar** [comment]
@jtdavis247 I don't know what could be going wrong then at this stage. It would appear everything is working as it should Can you please share the application with me so I can take a look at it?

Thanks.

**Comment by jtdavis247** [comment]
my app can be found at https://github.com/jtdavis247/game/commits/master. Thank you @radar!!

**Comment by radar** [comment]
@jtdavis247 I suspect this is because you're using two classes to represent users within your application: `User` and `Admin`. Why are you doing this? What is wrong with having one class to represent everybody?

**Comment by jtdavis247** [comment]
@radar I just followed https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-role which describes how to generate an admin with devise. If thats not a good approach I destroyed that with rails destroy devise admin. is that all that would need to be done ?

**Comment by radar** [comment]
@jtdavis247 I would just stay with the one User model (because that's all Forem is designed to work with) and implement your roles using a join table from `users` to another table called `roles`.

**Comment by jtdavis247** [comment]
Never mind! Got it man! Thank you! thank you Thank you!@radar == Lifesaver

**Comment by parndt** [comment]
# => true

**Pull request merged**
