### PR TITLE
ApproveAllTopicsAndPosts

### PR DESCRIPTION
**Pull request by glebm**
`rake spec' green

### CODE REVIEW

**Comment by parndt** [comment]
So we have to manage updated_at manually? I suppose that makes sense.

@radar?

**Comment by radar** [comment]
Why are you setting the updated_at field? I am not sure I understand that part.

**Comment by parndt** [comment]
I'm guessing because the hook that normally would is being bypassed?

**Comment by radar** [comment]
What effect does setting it have though other to indicate when the topic was approved at? Afaik we don't use it anywhere in forem.

**Comment by glebm** [comment]
@parndt Yes, but of course we don't want that hook here (because the existing sort order on updated at would break?)
@radar Updated!

**Comment by radar** [comment]
Update all is definitely a more sensible choice. Thanks :)

**Pull request merged**
