### PR TITLE
Stuff

### PR DESCRIPTION
**Pull request by glebm**
Finally did some work on forem:

```
CoffeeScript, JS packages (forem_admin, forem_admin_vendor)
Page titles as per #146
URL slugs using friendly_id (as discussed)
Admin views converted to HAML
Bugs fixed:
  * forums admin correctly groups by categories
  * concerns/viewable doesn't blow up if current_viewed_at is nil
  * members autocomplete now works and does not leak variables
```

### CODE REVIEW

**Comment by bearded** [comment]
@glebm, [rebase](http://help.github.com/rebase/) is better than revert ;-)

**Comment by glebm** [comment]
I agree, but rebase is scary!

> It is considered bad practice to rebase commits which you have already pushed to a remote repo. Doing so may invoke the wrath of the git gods... you have been warned.

So I do hope they let this one slide

**Comment by bearded** [comment]
Rebase is not so hard thing, and you can always do it while your branch is not merged into master in original repo.

One more problem that I can see, it is that you merged original repo in `stuff` branch, instead of merging it into your `master` and then merging `master` into `stuff` branch.

You can make next:

```
$ git checkout master

$ git remote add radar git://github.com/radar/forem.git
$ git fetch radar

$ git merge radar/master

$ git status
# On branch master
# Your branch is ahead of 'origin/master' by 73 commits.
#
nothing to commit (working directory clean)

$ git push
```

then you can rebase your brand:

```
$ git checkout stuff

$ git rebase master stuff
First, rewinding head to replay your work on top of it...
Applying: RubyMine in .gitignore
Applying: CoffeeScript, JS packages (forem_admin, forem_admin_vendor)
Applying: lil js fixes
Applying: Refs #148 Page Titles in content_for :forem_page_title, I18n
Applying: Admin members create -- response fix
Applying: Revert "RubyMine in .gitignore"

$ git status
# On branch stuff-old
# Your branch and 'origin/stuff' have diverged,
# and have 6 and 7 different commits each, respectively.
#
nothing to commit (working directory clean)

```

and git log will be much cleaner :)

```
$ git log
commit abdfb0f3246b81123bc1dfb2b0d8f4d63b47d78c
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 11:25:40 2012 +0200

    Revert "RubyMine in .gitignore"

    This reverts commit 44e79a33b0a83a6a9989fbe5f5ddc3550de47638.

commit 741cd11c8ccf1cd5ec8bab05130f389a9cd5f717
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 11:18:50 2012 +0200

    Admin members create -- response fix

commit 72f35c5ba4ab7babb765d8ab3bbe22593cabe84a
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 11:09:17 2012 +0200

    Refs #148 Page Titles in content_for :forem_page_title, I18n

commit dda99778bb2dec0c5d39ca55c024728ea9ff171e
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 10:44:12 2012 +0200

    lil js fixes

commit 8e8896e5e59c4a7afea9ba7bbf150248d2d83906
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 10:37:36 2012 +0200

    CoffeeScript, JS packages (forem_admin, forem_admin_vendor)
    Admin views converted to HAML
    Bugs fixed:
      * forums admin correctly groups by categories
      * concerns/viewable doesn't blow up if current_viewed_at is nil
      * members autocomplete now works and does not leak variables

commit 6cf43c785dbbd60e6a6d3e619d12eb2a27a4f588
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Tue Mar 20 19:53:58 2012 +0100

    RubyMine in .gitignore

commit 3c3e61c7af7282c3c5f4b1d100a81d55fe2f108b
Author: Ryan Bigg <radarlistener@gmail.com>
Date:   Fri Apr 13 12:18:53 2012 -0400

    Fix mistake in add_forem_view_fields migration as pointed out here: https://github.com/radar/forem/commit/19856a987ee36d77ed6e137fcc89cefe61974074#commitcomment-1207715
```

then you can make one more rebase to remove RubyMine commits like this:

```
$ git rebase -i 3c3e61c7af7282c3c5f4b1d100a81d55fe2f108b
```

comment needless commits in editor like here:

```
#pick 6cf43c7 RubyMine in .gitignore
pick 8e8896e CoffeeScript, JS packages (forem_admin, forem_admin_vendor) Admin views converted to HAML Bugs fixed:   * forums admin correctly groups by categories   * concerns/viewable doesn't blow up if current_viewed_at is nil   * members autocomplete now works and does not leak variables
pick dda9977 lil js fixes
pick 72f35c5 Refs #148 Page Titles in content_for :forem_page_title, I18n
pick 741cd11 Admin members create -- response fix
#pick abdfb0f Revert "RubyMine in .gitignore"

# Rebase 3c3e61c..abdfb0f onto 3c3e61c
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# If you remove a line here THAT COMMIT WILL BE LOST.
# However, if you remove everything, the rebase will be aborted.
#
```

save these changes

```
$ git status
# On branch stuff
# Your branch and 'origin/stuff' have diverged,
# and have 4 and 7 different commits each, respectively.
#
nothing to commit (working directory clean)

$ git log
commit d8b0240cc1eb5d00c32b6f397fc3cd1f18de3a79
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 11:18:50 2012 +0200

    Admin members create -- response fix

commit bcce90cb0222bda40cccd27db7ce16f941ba98b5
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 11:09:17 2012 +0200

    Refs #148 Page Titles in content_for :forem_page_title, I18n

commit cace06f6f64cbf2b4606296b2916e439f701f396
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 10:44:12 2012 +0200

    lil js fixes

commit 72624eaa3d61090f710ece8fff211f8e7c3994fa
Author: Gleb Mazovetskiy <glex.spb@gmail.com>
Date:   Sat Apr 14 10:37:36 2012 +0200

    CoffeeScript, JS packages (forem_admin, forem_admin_vendor)
    Admin views converted to HAML
    Bugs fixed:
      * forums admin correctly groups by categories
      * concerns/viewable doesn't blow up if current_viewed_at is nil
      * members autocomplete now works and does not leak variables

commit 3c3e61c7af7282c3c5f4b1d100a81d55fe2f108b
Author: Ryan Bigg <radarlistener@gmail.com>
Date:   Fri Apr 13 12:18:53 2012 -0400

    Fix mistake in add_forem_view_fields migration as pointed out here: https://github.com/radar/forem/commit/19856a987ee36d77ed6e137fcc89cefe61974074#commitcomment-1207715
```

then make force push and pull request will be much cleaner :)

```
$ git checkout master

$ git push origin stuff --force
```

**Comment by glebm** [comment]
Thanks! 
Спасибо, завтра попробую :)

**Comment by bearded** [comment]
not at all :)

**Comment by glebm** [comment]
OK, done!

**Comment by bearded** [comment]
Well done, from now rebase should not scare you ;-)

**Comment by radar** [comment]
First: I appreciate the amount of work that has gone into this patch.

Second: I strongly disagree with the changes in this patch. The large number of them makes it very hard to review just one group of changes at a time. Please consider splitting these different groups into separate pull requests so that they're easier to manage for us.

Third: I would rather the views for the admin section, or for that fact, _any_ section of Forem were _not_ converted into haml. I am personally much more comfortable with ERB.

Every other change there I would be fine with, just as long as they're in entirely different patches.

**Comment by jasonnoble** [comment]
@radar I think you meant "any section of Forem were <b>not</b> converted into haml"...

**Comment by radar** [comment]
Thanks @jasonnoble, fixed.

**Comment by parndt** [comment]
I agree with @radar

**Comment by parndt** [comment]
An API like `set_forem_page_title` is not a premature abstraction from a technical debt perspective; it allows us to refactor the internals at any point while maintaining a consistent interface.

**Pull request closed without merging**
