### PR TITLE
Url slugs

### PR DESCRIPTION
**Pull request by glebm**
Please take a look at this draft implementation for URL slugs

Provides a default of "#{name}-#{id}", and allows to override it with pretty much anything

### CODE REVIEW

**Comment by parndt** [comment]
Couldn't we just use [friendly_id](/norman/friendly_id#readme) for this?

**Comment by glebm** [comment]
Nice, didn't know about friendly_id. Looks great!
Although I am always a bit suspicious towards gems that override ActiveRecord::Base.find

**Comment by parndt** [comment]
It only overrides on the models where you want it to by specifying (for example): 

class MyModel < ActiveRecord::Base
  extend FriendlyId

  friendly_id :title, :use => :slugged
end

I've been using it for years and it works well from my perspective. Of course I've been added as a collaborator to it to declare my bias ;-)

**Comment by radar** [comment]
+1 for friendly_id

**Comment by glebm** [comment]
OK then, I'll implement friendly_id :)

**Comment by parndt** [comment]
@glebm thanks :-)

**Pull request closed without merging**
