### PR TITLE
Models cleanup

### PR DESCRIPTION
**Pull request by nashby**
- approved? method is granted by workflow gem
- it's possible to pass array to validates method
- remove obsolete code in approved scope

### CODE REVIEW

**Comment by radar** [comment]
Thanks for doing this!

**Comment by nashby** [comment]
@radar no problem! :) 
BTW, what do you think about using https://github.com/ernie/squeel/ instead of using Arel directly? I can work on it if it sound OK to you.

**Comment by radar** [comment]
What benefits would that provide?

**Comment by nashby** [comment]
Much more cleaner syntax.

**Comment by radar** [comment]
Do you have some examples of this?

**Comment by nashby** [comment]
``` ruby
where("forem_topics.state = ? OR " +
      "(forem_topics.state = ? AND forem_topics.user_id = ?)",
       'approved', 'pending_review', user.id)
```

becomes 

``` ruby
where { (forem_topics.state = 'approved') | ((forem_topics.state = 'pending_review' ) & (forem_topics.user_id = my { user.id })) }
```

or something like this.

**Comment by radar** [comment]
@parndt wdyt?

**Comment by parndt** [comment]
I am in favour of not introducing more dependencies if it is just
syntactic sugar.  If we need to do something that squeel can do and
arel can't then it is a different story but I don't think this is the
case.

**Comment by radar** [comment]
Ok, I can see that point in the argument. Makes sense to not include another dependency.

**Comment by nashby** [comment]
Ok, I see.

**Pull request merged**
