### PR TITLE
Link in forum description

### PR DESCRIPTION
**Pull request by radar**
I'd like to add a link to the forum description. Using GFM successfully.  No luck getting a link to parse in a forum description tho.  Must be missing something.  Help?

### CODE REVIEW

**Comment by radar** [comment]
@parndt Review kthx.

**Comment by parndt** [comment]
Seems legit :+1:

**Comment by radar** [comment]
<3

**Comment by plainspace** [comment]
thanks!

**Comment by plainspace** [comment]
hmmm... i thought this was working but no dice.  anyone else?

**Comment by radar** [comment]
Jared: please show us your Gemfile.lock file. The tests for this feature
are definitely working. The only ways I can think that it wouldn't be
working is if you didn't include the forem-redcarpet gem or didn't update
forem.

**Comment by plainspace** [comment]
I updated forem with the line of code you committed to app/views/forem/forums/_forum.html.erb.

```
GIT
  remote: git://github.com/Miniand/forem-gfm_formatter.git
  revision: 07efc0382784c762c995fe17dea41f94ececdd38
  specs:
    forem-gfm_formatter (1.0.0)
      forem
      redcarpet (~> 2.0.1)
```

```
GIT
  remote: git://github.com/radar/forem.git
  revision: 79ac5972a915b5de24ed382b0cf2d4740e64f186
  specs:
    forem (1.0.0.beta1)
      cancan (= 1.6.7)
      forem-redcarpet (= 1.0.0)
      friendly_id (~> 4.0)
      gemoji (~> 1.1.1)
      rails (~> 3.1)
      simple_form
      workflow (= 0.8.0)
```

```
forem-redcarpet (1.0.0)
      pygments.rb (= 0.2.4)
      redcarpet (= 2.0.1)
```

```
redcarpet (2.0.1)
```

```
redcarpet
```

**Comment by radar** [comment]
Looks like you're on an older version of forem: https://github.com/radar/forem/commit/79ac5972.

Please run `bundle update forem`.

**Comment by plainspace** [comment]
ok... updated forem. working now. thanks!  this is working in the the main forums view (forem/_forum.html.erb) but not in the forem/forums/show.html.erb

**Comment by radar** [comment]
^ That commit has fixed it on the show template and the admin backend. Thank you again.

**Comment by parndt** [comment]
Wow we must have great test coverage.

**Comment by plainspace** [comment]
Thanks mates!

**Pull request closed without merging**
