### PR TITLE
More detailed view tracking + visual indication of new topics

### PR DESCRIPTION
**Pull request by jgadbois**

### CODE REVIEW

**Comment by jgadbois** [comment]
Still need some specs for overall view tracking of forums and topics.  Also specs for register_view_by(user) to make sure that is only updating timestamps when appropriate.

**Comment by jgadbois** [comment]
@radar - Added specs - think this is good to go.  Please let me know what you think.

**Comment by radar** [comment]
Yup, seems good. @parndt, go for it!

**Comment by parndt** [comment]
Did it live

**Comment by jgadbois** [comment]
Thanks guys!

**Pull request merged**
