### PR TITLE
Update config/locales/ru.yml

### PR DESCRIPTION
**Pull request by greendog**

### CODE REVIEW

**Comment by radar** [comment]
Thank you! Happy holidays!

**Comment by parndt** [comment]
С Рождеством

**Comment by greendog** [comment]
> > С Рождеством

Ah-ha-ha :)
Excellent guys! 
And you too, Merry Christmas! == И вас тоже с Рождеством! (in Russian)

**Comment by radar** [comment]
This commit seems to break the build: http://travis-ci.org/#!/radar/forem/jobs/444963. Would it be possible for you (@greenodg) to look into this to see what it is breaking on? I'd figure you'd know more about that Russian translation file than I would.

Thanks!

**Comment by greendog** [comment]
Hmmm..
I immediately check it.

**Comment by greendog** [comment]
Fixed https://github.com/radar/forem/pull/105

**Pull request merged**
