### PR TITLE
Switched first and last on topic listing posts to get the correct one.

### PR DESCRIPTION
**Pull request by STRd6**
I'm not sure if this is the best place for this fix, but I noticed that the latest and started by were reversed.

### CODE REVIEW

**Comment by parndt** [comment]
Is there a default scope that sets order by created at DESC? I ask because I find it strange that it'd be like this otherwise :)

**Comment by STRd6** [comment]
Not sure, looking at the posts association in the Topic model it seemed like it should be the other way but they end up swapped in the view. Take a look at http://forem.heroku.com/, it exhibits the error.

**Comment by parndt** [comment]
@radar ?

**Comment by radar** [comment]
forem.heroku.com could be exhibiting this error as it hasn't been deployed to in a while. I believe we have tests that are now covering this issue and since all the tests are passing I don't believe that this is an issue. If you can create a test case that reproduces this issue then I'd be happy to review again.

**Pull request closed without merging**
