### PR TITLE
fix #272 - fix undefined method user for nil:NilClass error when visiting forum which has pending review

### LINKED ISSUE #272: undefined method `user' for nil:NilClass when visiting forum after creation new topic(unapproved)
undefined method `user' for nil:NilClass when visiting forum after creation new topic(unapproved)

Follow this steps to produce
- Sign up new user or (login with existing user but forem_state must be equal to pending_review for that user)
- Visit any forum
- Create new topic
- Visit that forum again

### PR DESCRIPTION
**Pull request by kunalchaudhari**
fix undefined method user for nil:NilClass error when visiting forum which has pending review.

### CODE REVIEW

**Comment by radar** [comment]
Could you write a regression test for this issue please?

**Comment by avitus** [comment]
We're also getting this error. Appears be related to posts that haven't been moderated (?)

**Comment by kunalchaudhari** [comment]
@avitus yeah. that happens because `relevant_posts(topic)` returns `[]` if topic has not been moderated yet. but if user who has started this post is logged in than topic should be displayed. And for other it won't show up as topic was not approved.

**Comment by avitus** [comment]
Ok. It is keeping us motivated to get posts moderated quickly.

**Comment by kunalchaudhari** [comment]
@avitus you can try out patch in my above commit.

**Comment by radar** [comment]
Thank you @kunalchaudhari for reporting the issue and fixing it :)

**Pull request merged**
