### PR TITLE
Added lines, fixed issues and typos in Russian translation

### PR DESCRIPTION
**Pull request by bodrovis**

### CODE REVIEW

**Comment by bodrovis** [comment]
Not sure why the build is failing, but it would be nice to update translations, because i have missing translations in some pages of the forum (groups and forums management).

**Comment by bodrovis** [comment]
Could you please merge it? Or did i do something wrong?

**Comment by radar** [comment]
Added to rails4 and master. Sorry for the delay, @bodrovis.

**Comment by bodrovis** [comment]
@radar Thank you!

**Pull request closed without merging**
