### PR TITLE
Sort forums and categories by order

### PR DESCRIPTION
**Pull request by jengel3**
Unfortunately, there really isn't a way to make sure that your forums and categories are sorted in the order that you want. To make this possible, I've added a order field to categories and forums, which is the order that they will be sorted in.

I needed this, so if it's useless here, then feel free to close it, or let me know of any issues :smile:

### CODE REVIEW

**Comment by radar** [comment]
Hi @Jake0oo0, apologies for the late merge. This looks pretty useful. I'll add it!

**Comment by radar** [comment]
Actually, please give these parameters a different name than "order", as that's a reserved word in most SQL engines.

**Comment by jengel3** [comment]
Alright, will do so when I get a chance!

**Comment by radar** [comment]
Thank you :)

**Comment by ivgames** [comment]
Hah! i made it too)) where were your fixes before))

**Comment by jengel3** [comment]
Any idea what to name it instead @radar? I'm having trouble finding a word to replace it...

**Comment by yan-hoose** [comment]
How about "sort_order"?

**Comment by radar** [comment]
acts_as_list uses "position", so I would just go with that.

**Comment by jengel3** [comment]
#611

**Pull request merged**
