### PR TITLE
FIx for Issue #301

### PR DESCRIPTION
**Pull request by 0xCCD**

### CODE REVIEW

**Comment by parndt** [comment]
@radar @knewter @robyurkowski can you forsee any issues with this patch?

**Comment by radar** [comment]
No, I can't foresee any issues with this patch.

I think that we should go the way that Spree's solving this problem: defining a top-level `Spree` JavaScript variable and then [defining routes underneath that](https://github.com/spree/spree/blob/split_core/backend/app/views/spree/admin/shared/_routes.html.erb). That way, we wouldn't need this ugly Journey hack in place.

**Comment by parndt** [comment]
Plus then we'd have support for any sub URI cleanly and with only exposing specific routes.

**Comment by knewter** [comment]
+1

**Comment by radar** [comment]
I've got a branch called members-select2 which is implementing this. It currently doesn't allow you to actually _add_ a member, which is problematic. To be looked at later.

**Comment by knewter** [comment]
@radar @parndt So is the strategy to close this PR and await the top level js variable?  Is there an issue open for doing that?

**Comment by radar** [comment]
@knewter: Yes, a top-level variable would be best. I don't think there's an open issue for fixing that other than #301.

**Comment by daniely** [comment]
the link to defining routes by @radar is gone. i believe this is the [correct link](https://github.com/spree/spree/blob/master/backend/app/views/spree/admin/shared/_routes.html.erb)

**Comment by bodrovis** [comment]
I am sorry, but was that ever fixed? I got the following error when visiting "Add a new member page": `TypeError: $(...).select2 is not a function` (I have created a brand new application with the latest Forem). Adding `gem "select2-rails"` directly to my Gemfile, `//= require select2` to application.js and `@import 'select2.css.scss';` to application.css.scss actually fixes this and everything works fine.

**Comment by bodrovis** [comment]
Oh, I just added `//= require forem` to application.js and `@import 'forem/base.css';` to application.css.scss. This should be mentioned somewhere in the docs probably?

**Comment by radar** [comment]
@bodrovis Yes, it should definitely be mentioned in the docs. Please submit a patch to fix that.

**Comment by bodrovis** [comment]
@radar Done: https://github.com/radar/forem/pull/502

**Pull request closed without merging**
