### PR TITLE
Autocomplete URL fix for forem JS + fixes

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by knewter** [comment]
So I can't help but notice there was a global in there before you updated this :)  I haven't tried out this code yet to verify it works - anyone else want to comment on it before a merge?

**Comment by glebm** [comment]
I haven't tried it out either!
Later this week I'm going to take a look at all the javascripts

**Comment by knewter** [comment]
I'll wait to merge until someone has verified that it works then :)

**Comment by gabrielbaez** [comment]
knewter!  nice to see another github user from the  birmingham,AL  area :)

**Comment by knewter** [comment]
@gabrielbaez ever come to the BOSS meetup?  I run a local ruby/rails consultancy here in town, we host it (Isotope11).  @everyoneelse - lol sorry this is apparently now our personal instant message suck it

**Comment by gabrielbaez** [comment]
I have not been there, but I think I have heard of it from an old co-worker that has been there "Clay"  is it close to the Inverness area?

**Comment by knewter** [comment]
maybe you should email me at josh at isotope11 dot com :)  And Isotope11's smack in the middle of homewood / valley ave.

**Comment by parndt** [comment]
So wait.. nobody has tried this out?

**Comment by gabrielbaez** [comment]
nope!

**Comment by parndt** [comment]
@glebm did you end up looking at all the javascripts?

**Comment by glebm** [comment]
I looked at them, but I didn't have time to change anything.

A few issues I identified:
- Needs to be modularized (Backbone.js anyone?)
- Leaks global variables a lot (using CoffeeScript would fix this)
- Does not use JavaScript naming conventions (i.e camelCase)
- Is included in head, which causes issues when a custom template is being used. A better practice would be to include it in a custom yield block, e.g. "content_for :forem_js do"

**Comment by parndt** [comment]
@glebm are you happy to take ownership of this issue?

I think that all except backbone would see instant merges. Backbone is more of an overhaul change ;-)

**Comment by glebm** [comment]
Sure. I will only be able to start working on it in May though

**Comment by glebm** [comment]
Actually, I had some time today :) 
See new pull request, closing this one

**Pull request closed without merging**
