### PR TITLE
Email subscriptions

### PR DESCRIPTION
**Pull request by jgadbois**
Work on issue #101

### CODE REVIEW

**Comment by radar** [comment]
Why are there SO MANY commits on this pull request? What happened, mate?

**Comment by radar** [comment]
Actually I think I may know what happened. You forked from master before I did the force push. If you pull origin/master to a new branch called email_subscriptions for example, and then cherry-pick your commits across onto this new branch and then submit a new pull request it should only have the right commits.

**Comment by jgadbois** [comment]
Ahh...I was confused about that too.

I'll try that.

**Comment by jgadbois** [comment]
Resubmitted - that should be a lot cleaner.  Still a work in progress but looking for early feedback.

**Pull request closed without merging**
