### PR TITLE
Forem.base_path does not have trailing slash

### PR DESCRIPTION
**Pull request by jgadbois**

### CODE REVIEW

**Comment by parndt** [comment]
Weird that we don't just use named routes

**Comment by jgadbois** [comment]
In the js file?

**Comment by parndt** [comment]
Yeah we could consider .js.erb cc @radar @knewter

**Comment by radar** [comment]
I wasn't aware that routes would work in an asset file.

**Comment by jgadbois** [comment]
If you can that would work fine for the autocomplete path, but not for the groups path.

**Pull request merged**
