### PR TITLE
Problem using Admin as #user_class

### PR DESCRIPTION
**Pull request by kot-begemot**
Recently i faced a problem, trying to specify "Admin" as Forem.user_class.
the error i got was something

Undefined method 'scope' for Forem::Admin module.

The solution I end up with is following:

String representing constant name should contain TopLevel reference. 
In order to keep backward compatibility, class_name_string method was implemented.

Tests are added.

Check out commit.

### CODE REVIEW

**Comment by parndt** [comment]
So previously it wouldn't work if you specified Forem.user_class = "::Admin" ?

**Comment by kot-begemot** [comment]
No... i tried both "::Admin" and "Object::Admin".
Point why it was not working:
Internally, user_class constantizd string, so it returned Admin constant in all cases "Admin", "::Admin" and "Object::Admin". After that it used to call to_s method on constant, so it was "Admin" in any case. 
Since Admin module is defined inside Forem module, it was be the first match....

**Comment by parndt** [comment]
I've discussed this with @radar and we wonder about using:

``` ruby
Object.const_get(Forem.user_class)
```

To get around the issue without having to introduce all this code. @radar is investigating further.

**Comment by parndt** [comment]
@radar @kot-begemot I stlll think some of the tests are valuable.

**Comment by radar** [comment]
Thank you for the patch.

I've modified it (3a2c4c1) so that we are using `Object.const_get(@@user_class)` to get the constant from the top-level, like we should. This means that I've undone some of your changes, but I have also kept the others such as the model spec which test that this behaviour is not broken.

**Comment by parndt** [comment]
Great stuff :-)

**Comment by kot-begemot** [comment]
But that will not solve the problem still.
Here is why:

Object.const_get(Forem.user_class)
 # => Admin(...)

Admin is correct constant - true, but, later (in case Forem::Topic class)

```
module Forem
  class Topic < ActiveRecord::Base
    ...
    belongs_to :user, :class_name => Forem.user_class.to_s
    ...
  end
end
```

So what will happen again, is the same thing,

Admin.to_s => "Admin"

And since the code is inside Forem module, and Admin module exsist in it as well, it will be the first option to pick up.

So, belongs to will pick up Forem::Admin, instead ::Admin....

**Comment by radar** [comment]
I've gone with something similar to your original situation in order to fix this problem. I really wish there was an easier way to get the relative-to-toplevel path for a constant, but I couldn't find one.

**Comment by kot-begemot** [comment]
I also do not like this way, it look hackish to me.

**Comment by radar** [comment]
Agree. It's the best that we can come up with for now, unfortunately.

**Comment by parndt** [comment]
Can we please use pull requests for changes to master as your last commit broke the tests?

**Comment by kot-begemot** [comment]
Note sure what you mean?

**Comment by parndt** [comment]
@radar This code still has issues with namespaced constants as is the case with #335

See http://stackoverflow.com/questions/4455676/how-do-i-refer-to-a-submodules-full-path-in-ruby#comment7410257_4457315

A constant like Refinery::User will never work, will it? 
It appears to work better when I specify Refinery.const_get("User") though.

**Comment by kot-begemot** [comment]
There is still problem presented there while generation task is executed. Here are more details:

```
~/projects$ rails g forem:install
The method 'YAML.enable_arbitrary_object_deserialization!' is deprecated and will be removed in the next release of SafeYAML -- set the SafeYAML::OPTIONS[:default_mode] to either :safe or :unsafe.
Copying over Forem migrations...
The method 'YAML.enable_arbitrary_object_deserialization!' is deprecated and will be removed in the next release of SafeYAML -- set the SafeYAML::OPTIONS[:default_mode] to either :safe or :unsafe.
What is your user class called? [User] Admin
What is the current_user helper called in your app? [current_user] current_admin
Defining forem_user method inside ApplicationController...
      insert  app/controllers/application_controller.rb
Skipping config/initializers/forem.rb creation, as file already exists!
Running rake db:migrate
The method 'YAML.enable_arbitrary_object_deserialization!' is deprecated and will be removed in the next release of SafeYAML -- set the SafeYAML::OPTIONS[:default_mode] to either :safe or :unsafe.
Creating default forum and topic
/home/.../gems/forem/app/models/forem/topic.rb:143
post.user = user
(rdb:1) list
[138, 147] in /home/.../gems/forem/app/models/forem/topic.rb
   138  
   139      protected
   140      def set_first_post_user
   141        post = posts.first
   142        require "ruby-debug"; debugger 
=> 143        post.user = user
   144      end
   145  
   146      def skip_pending_review
   147        if user.try(:forem_needs_moderation?)
(rdb:1) p user
#<Admin id: 6, ...>
(rdb:1) c
/home/.../gems/forem/app/models/forem/topic.rb:143
post.user = user
(rdb:1) p user
NoMethodError Exception: undefined method `scoped' for Forem::Admin:Module
(rdb:1) c
/home/.../gems/activerecord-3.2.12/lib/active_record/associations/association.rb:123:in `target_scope': undefined method `scoped' for Forem::Admin:Module (NoMethodError)
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/association.rb:87:in `scoped'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/singular_association.rb:42:in `find_target'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/association.rb:145:in `load_target'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/association.rb:55:in `reload'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/singular_association.rb:9:in `reader'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/builder/association.rb:44:in `block in define_readers'
    from /home/.../gems/forem/app/models/forem/topic.rb:143:in `set_first_post_user'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:451:in `_run__746503847__save__590235719__callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:84:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/validations.rb:50:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `block in save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:258:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:181:in `update_attribute'
    from /home/.../gems/forem/app/models/forem/post.rb:112:in `set_topic_last_post_at'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:409:in `_run__751752568__create__590235719__callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `create'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:348:in `create_or_update'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:447:in `_run__751752568__save__590235719__callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:84:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/validations.rb:50:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `block (2 levels) in save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:259:in `block in save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:258:in `save'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/associations/has_many_association.rb:16:in `insert_record'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:346:in `block in save_collection_association'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:337:in `each'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:337:in `save_collection_association'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:191:in `block in add_autosave_association_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:161:in `instance_eval'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/autosave_association.rb:161:in `block in define_non_cyclic_method'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:413:in `_run__746503847__create__590235719__callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_create_callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:268:in `create'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:348:in `create_or_update'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `block in create_or_update'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:458:in `_run__746503847__save__590235719__callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/callbacks.rb:264:in `create_or_update'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/persistence.rb:104:in `save!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/validations.rb:56:in `save!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:264:in `block in save!'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
    from /home/.../gems/activerecord-3.2.12/lib/active_record/transactions.rb:264:in `save!'
    from /home/.../gems/forem/db/seeds.rb:18:in `<top (required)>'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
    from /home/.../gems/railties-3.2.12/lib/rails/engine.rb:520:in `load_seed'
    from /home/.../gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/.../gems/forem/lib/generators/forem/install_generator.rb:67:in `seed_database'
    from /home/.../gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
    from /home/.../gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /home/.../gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
    from /home/.../gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
    from /home/.../gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
    from /home/.../gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
    from /home/.../gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
    from /home/.../gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
    from /home/.../gems/railties-3.2.12/lib/rails/generators.rb:171:in `invoke'
    from /home/.../gems/railties-3.2.12/lib/rails/commands/generate.rb:12:in `<top (required)>'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/.../gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /home/.../gems/railties-3.2.12/lib/rails/commands.rb:29:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by RamakrishnanK** [comment]
I have also same problem please tell how to rectify

**Comment by radar** [comment]
Hi @kot-begemot and @RamakrishnanK, could you please try using the `fix-329` branch and let me know if that fixes your problems please?

**Pull request closed without merging**
