### PR TITLE
Redirect posts#show to topics#show

### LINKED ISSUE #557: Route for particular post
I am working on a custom email notifier and tried using the following to get a URL for a particular post that needed to be approved:

```
<%= link_to "Post on #{post.topic}",
forem.forum_topic_post_url(post.forum, post.topic, post) %>
```

It returns a link, but the link does not work... If `/edit` is appended to the URL, it does work.

Making this work will require defining the `show` action for posts. I propose redirecting to the topic path with the appropriate page parameter.

Does this sound like a good approach? Or maybe I'm missing a feature that forem already has?

Thanks.

### PR DESCRIPTION
**Pull request by alexcwatt**
This is to fix #557. (Last couple of commits.)

However, I'm having a bit of trouble with git, as you can see. This pull request is listing too many commits and I can't figure out how to fix that. Any tips?

### CODE REVIEW

**Comment by alexcwatt** [comment]
@radar I'm not sure how to get rid of all the extra commits... Any tips would be appreciated. Should I just delete my fork and start over?

**Comment by radar** [comment]
@alexcwatt Rebase on the `rails4` branch of forem: `git rebase rails4`. Then force-push your branch to GitHub.

**Comment by alexcwatt** [comment]
@radar OK, it looks like it mostly worked. Do I need to also find a way to remove the commits that came after mine?

I really do appreciate the help here, as I'm trying to figure out how to properly use Git and GitHub.

**Comment by radar** [comment]
@alexcwatt: Make sure that you're up-to-date with the latest rails4 branch, then git rebase and force push again. I am not sure what is causing these other commits to appear.

**Pull request closed without merging**
