### PR TITLE
Abstract forem user

### PR DESCRIPTION
**Pull request by knewter**
Abstracted current_user out to forem_user, to be defined by the mounting app.  In refinery, I wanted it to be current_member rather than current_user, and this was necessary.

### CODE REVIEW

**Comment by radar** [comment]
Are you able to update the README to tell people that they have to define this method now?

**Comment by parndt** [comment]
(Pretty please)

**Comment by parndt** [comment]
@knewter once you update the readme I'll click merge!

**Comment by knewter** [comment]
OK, I did it.  Sorry it took so long :)

**Comment by parndt** [comment]
<3 <3

**Comment by knewter** [comment]
Oh hey you merged it.  I thought scary conflicts kept that from happening :)  Awesome.

**Pull request merged**
