### PR TITLE
Run the dummy app with localeapp when an API key is supplied.

### PR DESCRIPTION
**Pull request by parndt**
Is this remotely approaching correct?

### CODE REVIEW

**Comment by radar** [comment]
What is this supposed to fix?

**Comment by parndt** [comment]
The sync of localeapp

**Comment by parndt** [comment]
@radar thoughts, comments?

**Comment by radar** [comment]
Seems fine to me

**Comment by parndt** [comment]
Localeapp is dead, long live Forem without Localeapp!

**Pull request closed without merging**
