### PR TITLE
able to use with rails 4.2.1 too

### PR DESCRIPTION
**Pull request by mpakus**

### CODE REVIEW

**Comment by yan-hoose** [comment]
Since there is a bug in Rails 4.2 that causes Forem to double-increment views, I don't recommend to use Forem with Rails 4.2 until that bug is fixed (https://github.com/radar/forem/issues/640).

If you are fine with that, go ahead! :smile:

**Comment by radar** [comment]
I am not fine with having Forem support a version of Rails with a known regression. Therefore I won't be accepting this PR until Rails 4.2.2 is released.

**Comment by senych-vitalii** [comment]
hey @radar Rails 4.2.2 is already released, can you accept PR?
Currently I cannot use Forem without this fix because I use 4.2.1 version of Rails...

**Comment by radar** [comment]
Does 4.2.2 contain the specified patch or is it just security releases?

**Comment by senych-vitalii** [comment]
@radar it seems not... 
Sorry, I missed that counter is working in 4.2 version and is not working in 4.2.1.

**Comment by yan-hoose** [comment]
Actually counter caches are broken in all of Rails 4.2 versions. Forem Rails dependency should be

``` ruby
s.add_dependency 'rails', '~> 4.0', '< 4.2'
```

instead of

``` ruby
s.add_dependency 'rails', '~> 4.0', '<= 4.2'
```

**Comment by radar** [comment]
I'm fine with leaving the dependency as it is now. If people complain about the counter cache issue, we can point them to this issue.

**Comment by edmondchui** [comment]
The counter issue is fixed in Rails 4.2.4. Could you please update the dependency to Rails 4.2.4, 4.2.5, and above? Thanks.

**Comment by sintro** [comment]
> The counter issue is fixed in Rails 4.2.4. Could you please update the dependency to Rails 4.2.4, 4.2.5, and above? Thanks.

Is not it already updated?

**Pull request closed without merging**
