### PR TITLE
add a missing closing div

### PR DESCRIPTION
**Pull request by jugyo**

### CODE REVIEW

**Comment by parndt** [comment]
@radar this wouldn't have happend with HAML :trollface:

**Comment by parndt** [comment]
Thanks @jugyo :thumbsup: :sunglasses:

**Comment by knewter** [comment]
Not even joking, this is my argument for an HTML preprocessor. Thanks.

**Comment by parndt** [comment]
@knewter Ryan would never go for it :wink:

**Comment by jugyo** [comment]
I like HAML :sunglasses:. Thank you for merging very quickly :+1:

**Pull request merged**
