### PR TITLE
Private forums

### PR DESCRIPTION
**Pull request by gabriel-dehan**
Enhance forum creation with the ability to create private forums for chosen groups

### CODE REVIEW

**Comment by radar** [comment]
This pull request appears to have a lot of other unrelated commits in it for the autocomplete stuff...

**Comment by gabriel-dehan** [comment]
Oh damn I had not noticed (yaah, it's late), my bad, I'll clean that up and submit a clean pull request ;)

Thanks.

**Comment by kunalchaudhari** [comment]
@gabriel-dehan can you have look at issue #271? its something like open forums. Invert of private forums i guess but not exactly.

**Comment by parndt** [comment]
Closing due to this PR having too many commits and being stale - please open a new one if you wish - thanks!

**Pull request closed without merging**
